[[platforms]]
os = "jammy"
archs = ["aarch64", "x86_64", "riscv64"]
packages = [
  "libbsd-dev",
  "libbsd0",
  "libc6",
  "libc6-dev",
  "libedit-dev",
  "libedit2",
  "libgcc-11-dev",
  "libgcc-s1",
  "libmd-dev",
  "libmd0",
  "libncurses-dev",
  "libncurses6",
  "libstdc++-11-dev",
  "libstdc++6",
  "libtinfo6",
  "linux-libc-dev",
  "zlib1g-dev",
]
deleted_patterns = [
  "*.pc",
  "*/gconv.h",
  "*/libasan*",
  "*/libc.a",
  "*/libedit.a",
  "*/liblsan*",
  "*/libm-*.a",
  "*/libmd.a",
  "*/libpanel.a",
  "*/libstdc*.a",
  "*/libtinfo.a",
  "*/libtsan*",
  "*/libubsan*",
  "etc",
  "usr/bin",
  "usr/lib/*-linux-gnu/audit",
  "usr/lib/*-linux-gnu/gconv",
  "usr/lib/*-linux-gnu/pkgconfig",
  "usr/lib/valgrind",
  "usr/share",
]
